GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "Aku Ankan Blogi",
  "author": "Aku Ankka",
  "url": "localhost",
  "likes": 2
}

###

POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "author": "Aku Ankka",
  "url": "localhost",
  "likes": 2
}

###


POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "Aku Ankan Blogi",
  "author": "Aku Ankka",
  "likes": 2
}

###

DELETE http://localhost:3003/api/blogs/
content-type: application/json

###

PUT http://localhost:3003/api/blogs/5d9f3d65e1140d4449f20dba
content-type: application/json

{
  "likes": 7
}