GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI1ZGE5ZjdhOTliMzJhNDUxODhhZGYzMzUiLCJpYXQiOjE1NzE0MjMxNTR9.8cr29i6Fgok0DUcP1QdPJ6pI2gMdxc0U02RlOe27hto

{
  "title": "Uusi Blogi",
  "author": "Aku Ankka",
  "url": "localhost",
  "likes": 3
}

###

POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "author": "Aku Ankka",
  "url": "localhost",
  "likes": 2
}

###


POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "Aku Ankan Blogi",
  "author": "Aku Ankka",
  "likes": 2
}

###

DELETE http://localhost:3003/api/blogs/
content-type: application/json

###

PUT http://localhost:3003/api/blogs/5d9f3d65e1140d4449f20dba
content-type: application/json

{
  "likes": 7
}